name: execute_script

description: execute a bash script

inputs:
  step_name:
    description: "used for naming the step execution"
    required: true
  script_parameter:
    description: "command line instruction for executing a script"
    required: true
  working_directory:
    description: "working directory for the script execution"
    required: false
    default: "."
  if:
    description: "conditional execution of the step"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: ${{inputs.step_name}}
      shell: bash
      run: |
        ${{inputs.script_parameter}}
      working-directory: ${{inputs.working_directory}}